import Head from 'next/head';
import { Inter } from '@next/font/google';
import { Container } from '@/app/providers/Layout';
import { SubHeader } from './sections/sub-header';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Webtronics</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container>
        <SubHeader />
      </Container>
    </>
  );
}
