import Head from 'next/head';
import { Layout } from '@/shared/lib/components';
import { About } from './sections/about';

export default function Home() {
  return (
    <Layout subHeader>
      <Head>
        <title>Webtronics</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <About />
    </Layout>
  );
}
